// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Json2 is an autogenerated mock type for the Json2 type
type Json2 struct {
	mock.Mock
}

// Marshal provides a mock function with given fields: obj
func (_m *Json2) Marshal(obj interface{}) ([]byte, error) {
	ret := _m.Called(obj)

	var r0 []byte
	if rf, ok := ret.Get(0).(func(interface{}) []byte); ok {
		r0 = rf(obj)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(interface{}) error); ok {
		r1 = rf(obj)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Unmarshal provides a mock function with given fields: obj, caster
func (_m *Json2) Unmarshal(obj []byte, caster interface{}) error {
	ret := _m.Called(obj, caster)

	var r0 error
	if rf, ok := ret.Get(0).(func([]byte, interface{}) error); ok {
		r0 = rf(obj, caster)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
