version: '3.3'
services:
    node-app:
        container_name: 'node-app'
        build: .
        volumes:
            -   .:/app
            - node_modules:/app/node_modules
        ports:
            -   7314:7314
        stdin_open: true
        command:
            -   npm start
volumes:
    node_modules:

